FROM alpine as build

ARG BUILD_DATE
LABEL build-date=$BUILD_DATE

RUN apk add --update --no-cache alpine-sdk git openssl-dev zlib-dev
RUN git clone https://github.com/giltene/wrk2.git --no-checkout --single-branch --branch master wrk2 &&\
    cd wrk2 &&\
    git checkout 44a94c17d8e6a0bac8559b53da76848e430cb7a7
WORKDIR /wrk2
RUN make

FROM alpine
RUN apk add --update --no-cache libgcc openssl
COPY --from=build /wrk2/wrk /usr/bin/wrk2
ENTRYPOINT ["wrk2"]

