name: ci

on:
  push:
    tags:
      - '*/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set envvars tag_name/tag_version from GITHUB_REF
        run: |
          echo "TAG_NAME=$(echo ${GITHUB_REF} | cut -d'/' -f3)" >> $GITHUB_ENV
          echo "TAG_VER=$(echo ${GITHUB_REF} | cut -d'/' -f4)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./${{ env.TAG_NAME }}/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.TAG_NAME }}:${{ env.TAG_VER }}

      - uses: actions/checkout@v3

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.TAG_NAME }}
          short-description: Tiny size wrk2 image - HTTP benchmarking tool
          readme-filepath: ./${{ env.TAG_NAME }}/README.md
